//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DmseBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Information {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Information() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DmseBot.Information", typeof(Information).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students complete relevant projects that require employing various Software Engineering development methodologies and industry practices. Each project is designed to prepare them to seamlessly integrate into the workforce and begin productive and exciting careers.
        ///
        ///Most projects are selected by the student. The students have the opportunity to develop software applications for the desktop, Internet, tablets, smart phones, robotics, game consoles, virtual reality, and augmented reality.
        ///
        ///The DMSE program [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutDmse {
            get {
                return ResourceManager.GetString("AboutDmse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Apply
        ///What You Will NeedDigital Media Software Engineering
        ///
        ///Applying to DMSE is free. Of course, you will need a few things.
        ///
        ///Official high school transcripts. You will need at least a 2.7 GPA to apply as a freshman. Have your high school transfer your grades over to our registrar.
        ///Your ACT scores of 21 or above. The ACT is a national college admission and placement examination.
        ///Official college or university transcripts from any institution you have previously attended.
        ///Send your transcripts [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApplyForDmse {
            get {
                return ResourceManager.GetString("ApplyForDmse", resourceCulture);
            }
        }
    }
}
